import { Geist, Geist_Mono, Noto_Serif_Display } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSerifDisplay = Noto_Serif_Display({ 
  subsets: ['latin'] 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
    <html lang="en" className={notoSerifDisplay.className}>
      <body>{children}</body>
    </html>
  );
}
